# Gryphon T/P Sessions Python Phase II Day 1

## Creating Arrays and Importing Numpy

In [ ]:
import numpy as np
# print(np.__version__)
#to check version of numpy installed

# to create 1d array
n1 = np.array([1, 2, 3, 4, 5])

# to create 2d array
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# printing dimention of array
print(n1.ndim)
print(n2.ndim)
print()


# printing shape of array
print(n1.shape)
print(n2.shape)
print()


#  to create a array from given ranges(start,stop,step) we can use
# arrange()
n3=np.arange(25)
print(n3)
print()

## Arange() 
Arange is used to create an Array with values mentioned in the range like (Start,Stop,Step ) format

In [39]:
n3=np.arange(9).reshape((3,3))
print(n3)
print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## Ones ()
it gives arrays of 1's but its default datatype is float 
to change the datatype we have change an attritube of function name dtype to int

## Zeros()

it is similar to ones but for zero

In [ ]:
# ones()
# it gives arrays to 1'set
n4=np.ones((3,4),dtype=int)
print(n4)
print()
# similarly zeros()
# it gives arrays of zero

n5=np.zeros((3,4),dtype=int)
print(n5)

## Linespace() 
if creates a dummy array with a start point and end point with deafult 50 numbers and can have endpoint set to true or fallse

In [ ]:
n6=np.linspace(10,20)
print(n6)
print()

n7=np.linspace(10,20,num=5,endpoint=False)
print(n7)

[10. 12. 14. 16. 18.]

## Transpose ()

it converts the rows into column and vice versa

In [40]:
n8=np.arange(1,7).reshape((2,3))
print(n8)
print()
n9=np.transpose(n8)
print(n9)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

# Pandas 
Pandas is a Python library used for data manipulation, analysis, and cleaning. It works mainly with two data structures:

Series → 1D labeled array, 

DataFrame → 2D labeled table (rows and columns)

In [41]:
import pandas as pd
print(pd.__version__)

2.3.3

## Series 
* Series are the 1d LAbelled Arrays

* we can pass their list as well as dictonary

## Using Lists

In [47]:
l1=[1,2,3,"Pandas","Mbapu"]
s1=pd.Series(l1)
print(s1)
print()
# for custom indexes
s2=pd.Series(l1,index=['@','#','$','%',"&"])
print(s2)

0         1
1         2
2         3
3    Pandas
4     Mbapu
dtype: object

@         1
#         2
$         3
%    Pandas
&     Mbapu
dtype: object

## Using Dictonaries

In [49]:
d={'a':10,'b':20,'c':30}
s3=pd.Series(d)
print(s3)

a    10
b    20
c    30
dtype: int64

## DataFrames
2d Label Arrays

using list

In [51]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
d1=pd.DataFrame(l1,index=['a','b','c'],columns=["@","#","$"])
print(d1)

   @  #  $
a  1  2  3
b  4  5  6
c  7  8  9

Using dictonaries

In [55]:
d={
    "Names":["Ayush","Atharv","Kuldip"],
    "Age":[20,20,21],
    "Branch":["CSE","CSE","AIDS"]
}

d2=pd.DataFrame(d,index=["@","#","$"])
print(d2)

    Names  Age Branch
@   Ayush   20    CSE
#  Atharv   20    CSE
$  Kuldip   21   AIDS

## Acessing Files in CSV and Excel

In [64]:
df=pd.read_csv("/mnt/shared/7thsem/KDK-Gryphon-Training-Session/Python/Phase II/Datasets/student_result.csv")
df.tail()

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

## Accesing Data From CSV file

In [78]:
df[df["Class"]>10]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75