In [ ]:
for x in df11.columns:
  print (x,':',len(df11[x].unique()))

City : 2
Area : 5
Parking : 2

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
# used only for variblaes which has natural order like gender,education,review alphabetically
from sklearn.preprocessing import LabelEncoder
# wise versa of ordinal Encoder

In [62]:
from google.colab import files
uploaded = files.upload()

Saving Customer.csv to Customer (1).csv

In [63]:
df= pd.read_csv("Customer.csv")

In [64]:
df.head()

   Age  Gender Education   Review Purchased
0   30  Female    School  Average        No
1   68  Female        UG     Poor        No
2   70  Female        PG     Good        No
3   72  Female        PG     Good        No
4   16  Female        UG  Average        No

In [65]:
df.tail()

    Age  Gender Education Review Purchased
45   61    Male        PG   Poor       Yes
46   64  Female        PG   Poor        No
47   38  Female        PG   Good       Yes
48   39  Female        UG   Good       Yes
49   25  Female        UG   Good        No

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        50 non-null     int64
 1   Gender     50 non-null     object
 2   Education  50 non-null     object
 3   Review     50 non-null     object
 4   Purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [67]:
df.shape

(50, 5)

In [68]:
df['Education'].value_counts()

Education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [69]:
df['Review'].value_counts()

Review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [70]:
df['Purchased'].value_counts()

Purchased
No     26
Yes    24
Name: count, dtype: int64

In [71]:
df['Gender'].value_counts()

Gender
Female    29
Male      21
Name: count, dtype: int64

We have 4 Categorical Columns out of 2 are norminal and 2 are ordinal

Oridinal => Education and Review

norminal => Gender Purchased

# Working on Ordinal Categorial Variable

Seprating the Ordinal Categorical Value

In [72]:
df1=df.iloc[:,2:4]
df1.head(2)

  Education   Review
0    School  Average
1        UG     Poor

In [73]:
oe=OrdinalEncoder(categories=[['School','UG','PG'],['Poor','Average','Good']])

In [74]:
df1_oe=oe.fit_transform(df1)
df1_oe

array([[0., 1.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [1., 2.]])

The Obtained Data is in Array Form but we want in Dataframe Form So we HAve to Convert it

In [75]:
df1=pd.DataFrame(df1_oe,columns=['Education','Review'])
df1.head()

   Education  Review
0        0.0     1.0
1        1.0     0.0
2        2.0     2.0
3        2.0     2.0
4        1.0     1.0

In [76]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Education  50 non-null     float64
 1   Review     50 non-null     float64
dtypes: float64(2)
memory usage: 932.0 bytes

In [77]:
# converting Float dtype into Int dtype
df1=df1.astype('int')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Education  50 non-null     int64
 1   Review     50 non-null     int64
dtypes: int64(2)
memory usage: 932.0 bytes

# Label Encoder

In [78]:
df2=df.iloc[:,2:4]
df2.head(2)

  Education   Review
0    School  Average
1        UG     Poor

In [79]:
le=LabelEncoder()

In [80]:
df2['Education_new']=le.fit_transform(df2['Education'])
df2['Review_new']=le.fit_transform(df2['Review'])

In [81]:
df2.head()

  Education   Review  Education_new  Review_new
0    School  Average              1           0
1        UG     Poor              2           2
2        PG     Good              0           1
3        PG     Good              0           1
4        UG  Average              2           0

In [82]:
# working on norinal Categorical Variables
df3=df[['Gender','Purchased']]
df3.head(2)

   Gender Purchased
0  Female        No
1  Female        No

In [83]:
df3['Purchased_new']=le.fit_transform(df3['Purchased'])
df3['Gender_new']=le.fit_transform(df3['Gender'])

/tmp/ipykernel_1430/2496778234.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Purchased_new']=le.fit_transform(df3['Purchased'])
/tmp/ipykernel_1430/2496778234.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Gender_new']=le.fit_transform(df3['Gender'])

In [84]:
df3.head()

   Gender Purchased  Purchased_new  Gender_new
0  Female        No              0           0
1  Female        No              0           0
2  Female        No              0           0
3  Female        No              0           0
4  Female        No              0           0

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        50 non-null     int64
 1   Gender     50 non-null     object
 2   Education  50 non-null     object
 3   Review     50 non-null     object
 4   Purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [86]:
df[['Gender','Purchased']]=df3[['Gender_new','Purchased_new']].copy()
df.update(df1)
df.head()

   Age  Gender Education Review  Purchased
0   30       0         0      1          0
1   68       0         1      0          0
2   70       0         2      2          0
3   72       0         2      2          0
4   16       0         1      1          0

# Working on Nornimal Data

In [110]:
from google.colab import files
uploaded = files.upload()

Saving Nashik_House Price.csv to Nashik_House Price (2).csv

In [111]:
df4=pd.read_csv('Nashik_House Price.csv')

In [89]:
df4

      City           Area Flat_type Parking  Area_SqMeter  Price_Lakhs
0   Nashik   Govind Nagar     1 BHK      No         57.60        27.50
1   Nashik   Govind Nagar     1 BHK     Yes         59.45        31.20
2   Nashik   Govind Nagar     2 BHK     Yes         78.96        37.40
3   Nashik   Govind Nagar     3 BHK     Yes         97.55        47.10
4   Nashik  Gangapur Road     1 BHK     Yes         59.45        25.50
5   Nashik  Gangapur Road     2 BHK     Yes         80.80        30.50
6   Nashik  Gangapur Road     3 BHK     Yes        102.20        45.70
7   Nashik    Ashok Nagar      1 RK      No         41.80        17.80
8   Nashik    Ashok Nagar     1 BHK      No         60.10        25.20
9   Nashik    Ashok Nagar     2 BHK     Yes         82.70        30.50
10    Pune         Wagoli     1 BHK      No         53.80        34.40
11    Pune         Wagoli     1 BHK     Yes         55.20        37.65
12    Pune         Wagoli     2 BHK     Yes         72.90        51.51
13    Pune         Wagoli     3 BHK     Yes         85.40        62.78
14    Pune     Wadgaon_BK     1 BHK     Yes         56.70        31.70
15    Pune     Wadgaon_BK     2 BHK     Yes         71.80        42.70
16    Pune     Wadgaon_BK     3 BHK     Yes         71.80        52.80

In [112]:
df4.shape

(17, 6)

In [113]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          17 non-null     object
 1   Area          17 non-null     object
 2   Flat_type     17 non-null     object
 3   Parking       17 non-null     object
 4   Area_SqMeter  17 non-null     float64
 5   Price_Lakhs   17 non-null     float64
dtypes: float64(2), object(4)
memory usage: 948.0+ bytes

### Ordinal Encoding for `Flat_type`

In [ ]:
# Get unique values in 'Flat_type' to define order
print("Unique Flat Types:", df4['Flat_type'].unique())

# Define the desired order for 'Flat_type'
flat_type_order = ['1 RK', '1 BHK', '2 BHK', '3 BHK']

# Initialize OrdinalEncoder with the specified order
flat_type_encoder = OrdinalEncoder(categories=[flat_type_order])

# Fit and transform the 'Flat_type' column
df4['Flat_type_encoded'] = flat_type_encoder.fit_transform(df4[['Flat_type']])

# Display the updated DataFrame with the new encoded column
display(df4.head())

In [ ]:
# Optionally, drop the original 'Flat_type' column if no longer needed
df4 = df4.drop('Flat_type', axis=1)
display(df4.head())

In [114]:
df11=df4.select_dtypes(include='object')
df11.head()

     City           Area Flat_type Parking
0  Nashik   Govind Nagar     1 BHK      No
1  Nashik   Govind Nagar     1 BHK     Yes
2  Nashik   Govind Nagar     2 BHK     Yes
3  Nashik   Govind Nagar     3 BHK     Yes
4  Nashik  Gangapur Road     1 BHK     Yes

In [115]:
df11=df11.drop('Flat_type',axis=1)
df11.head()

     City           Area Parking
0  Nashik   Govind Nagar      No
1  Nashik   Govind Nagar     Yes
2  Nashik   Govind Nagar     Yes
3  Nashik   Govind Nagar     Yes
4  Nashik  Gangapur Road     Yes

In [118]:
for x in df11.columns:
  print (x,':',len(df11[x].unique()))

City : 2
Area : 5
Parking : 2

In [119]:
dummy_df=pd.get_dummies(df11)
dummy_df.head()

,City_Nashik,City_Pune,Area_Ashok Nagar,Area_Gangapur Road,Area_Govind Nagar,Area_Wadgaon_BK,Area_Wagoli,Parking_No,Parking_Yes
0,True,False,False,False,True,False,False,True,False
1,True,False,False,False,True,False,False,False,True
2,True,False,False,False,True,False,False,False,True
3,True,False,False,False,True,False,False,False,True
4,True,False,False,True,False,False,False,False,True

In [120]:
dummy_df=dummy_df.astype(int)
dummy_df.head()

,City_Nashik,City_Pune,Area_Ashok Nagar,Area_Gangapur Road,Area_Govind Nagar,Area_Wadgaon_BK,Area_Wagoli,Parking_No,Parking_Yes
0,1,0,0,0,1,0,0,1,0
1,1,0,0,0,1,0,0,0,1
2,1,0,0,0,1,0,0,0,1
3,1,0,0,0,1,0,0,0,1
4,1,0,0,1,0,0,0,0,1

In [122]:
dummy_df.shape

(17, 9)

# OneHot Encoder

In [125]:
from sklearn.preprocessing import OneHotEncoder
oh_enc=OneHotEncoder(sparse_output=False)
# sparse_output=False because we want the output in array format

In [126]:
oh_enc_arr=oh_enc.fit_transform(df11)
oh_enc_arr

array([[1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.]])

In [127]:
oh_enc=OneHotEncoder(sparse_output=False,drop='first')
oh_enc_arr=oh_enc.fit_transform(df11)
oh_enc_arr

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0., 1.]])

In [129]:
dummy_df.keys()

Index(['City_Nashik', 'City_Pune', 'Area_Ashok Nagar', 'Area_Gangapur Road',
       'Area_Govind Nagar', 'Area_Wadgaon_BK', 'Area_Wagoli', 'Parking_No',
       'Parking_Yes'],
      dtype='object')

In [131]:
oh_enc_df=pd.DataFrame(oh_enc_arr,columns=['City_Pune','Area_Gangapur Road','Area_Govind Nagar','Area_Wadgaon_BK','Area_Wagoli','PArking_Yes'])
oh_enc_df.head()

,City_Pune,Area_Gangapur Road,Area_Govind Nagar,Area_Wadgaon_BK,Area_Wagoli,PArking_Yes
0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,1.0

### Re-demonstrating Ordinal Encoding for `Flat_type`

In [139]:
df4_reloaded = pd.read_csv('Nashik_House Price.csv')
df4_reloaded.head()

     City           Area Flat_type Parking  Area_SqMeter  Price_Lakhs
0  Nashik   Govind Nagar     1 BHK      No         57.60         27.5
1  Nashik   Govind Nagar     1 BHK     Yes         59.45         31.2
2  Nashik   Govind Nagar     2 BHK     Yes         78.96         37.4
3  Nashik   Govind Nagar     3 BHK     Yes         97.55         47.1
4  Nashik  Gangapur Road     1 BHK     Yes         59.45         25.5

In [137]:
flat_type_encoder = OrdinalEncoder(categories=[['1 RK', '1 BHK', '2 BHK', '3 BHK']])
df4_reloaded['Flat_type_encoded'] = flat_type_encoder.fit_transform(df4_reloaded[['Flat_type']])
df4_reloaded.head()

,City,Area,Flat_type,Parking,Area_SqMeter,Price_Lakhs,Flat_type_encoded
0,Nashik,Govind Nagar,1 BHK,No,57.60,27.5,1.0
1,Nashik,Govind Nagar,1 BHK,Yes,59.45,31.2,1.0
2,Nashik,Govind Nagar,2 BHK,Yes,78.96,37.4,2.0
3,Nashik,Govind Nagar,3 BHK,Yes,97.55,47.1,3.0
4,Nashik,Gangapur Road,1 BHK,Yes,59.45,25.5,1.0